### ISSUE TITLE
Landing screen 

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#13]
# Landing Screen
This is the first screen that users will see when they launch the app
User can click on `Mapeo Data Is Detected` OR `Mapeo Is Not Detected` OR `Invite Device`

<img width="878" alt="Screen Shot 2023-04-10 at 4 31 58 PM" src="https://user-images.githubusercontent.com/78557542/230992684-7b1707f0-964e-49c9-b907-fb082b189e2e.png">

# ToDo:

- [x] Build Screen
- [x] OnClick  `Mapeo Data Is Detected` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/5
- [ ] OnClick `Mapeo Is Not Detected` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/14
- [ ] OnClick `Invite Device` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/22
- [x] Cannot multi-select

# Designs
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=0-1&t=E6LG66IHUCKXK0Mp-0
