### ISSUE TITLE
Mapeo 5 data not detected screen / No path / Join a project

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#17]
## Mapeo 5 data not detected screen / No path / Join a project
- User is on [the Mapeo 5 not detected screen](https://github.com/digidem/mapeo-desktop-shell/issues/14) and clicked on NO.  
- User clicked on `Join a project` 

<img width="738" alt="Screen Shot 2023-04-06 at 12 27 29 PM" src="https://user-images.githubusercontent.com/78557542/230439852-f641fc6f-9474-4e70-83ff-2041b48ab8f4.png">

## Todo
- [ ]  Create modal 
- [ ] Put placeholder text , Copy proposal: "End of path, please try go back to Home to test another path." 
- [ ] Should have `Close` button at the bottom right
- [ ] If `Close` button is clicked closes bottom sheet

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=0-1&t=4eZwdDiRxd883yDw-0
