### ISSUE TITLE
Mapeo 5 data not detected screen / No path / Create a project

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#18]
## Mapeo 5 data not detected screen / No path / Create a project
- User is on [the Mapeo 5 not detected screen](https://github.com/digidem/mapeo-desktop-shell/issues/14) and clicked on NO
- User clicked on `Create a project`  and this modal opens
- User filled all the info in the modal and clicked on the `Create a project` button and lands in the app on the Observation Mode

<img width="705" alt="Screen Shot 2023-04-03 at 7 57 59 PM" src="https://user-images.githubusercontent.com/78557542/229652098-9de3c0fa-7a6b-49b2-b9a6-2c52a75d3a8b.png">

<img width="719" alt="Screen Shot 2023-04-03 at 8 12 35 PM" src="https://user-images.githubusercontent.com/78557542/229653710-301503cc-0359-4f71-ad36-7c3ddad934dc.png">

## Todo

- [ ] Display modal as designed
- [ ] Display a text box titled  **Enter the name for the project**, max 100 characters
- [ ] Display a text box titled  **Add name for your device**, max 60characters
- [ ] Make both boxes to be mandatory to be able to  `Create project` 
- [ ] Display text  **Can participants see other team members observations?**
- [ ] Display radio button YES and NO , no multi-select, not mandatory to create a project
- [ ]  Display text  **Can participants edit other team members observations?**
- [ ] Display radio button YES and NO , no multi-select, not mandatory to create a project
- [ ]  Display text  **Project Config**
- [ ] Create button `Import Config` , not clickable
- [ ]  Display text  in the bottom bar and add the project name to the copy
- [ ] Display  `Close` button
- [ ] Display  `Create Project` button

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=0-1&t=4eZwdDiRxd883yDw-0

**Comment by ErikSin** [comment]
@lightlii Assigning this to you as you have already done this work on https://github.com/digidem/mapeo-desktop-shell/pull/48
