### ISSUE TITLE
Project Config / Pre-invite

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#22]
## Project Config / Pre-invite
- User was on the [Project Invite screen](https://github.com/digidem/mapeo-desktop-shell/issues/21) and landed on the project config screen
- User had not invited devices to this project before, so only display the coordinator device
- Only the `Join Project` and `Invite` are clickable
  

<img width="725" alt="Screen Shot 2023-04-10 at 1 53 14 PM" src="https://user-images.githubusercontent.com/78557542/230961491-18933468-3182-40d7-b8a1-9a5b48ac8316.png">

## Todo

- [ ] Build screen as designed 
- [ ] Build menu as designed
- [ ] Display  the `Join Project` which will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/17
- [ ] Display the `Invite` button which will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/25

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=4-623&t=jCsvYtfaEBof4KnS-0
