### ISSUE TITLE
Flow Navigation

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#24]
# Flow Navigation
The user is either the Migration or Project invite flow and would like to return to the landing screen or another flow.  User can access to different flows via the Desktop navigation bar.

<img width="287" alt="Screen Shot 2023-04-10 at 4 39 45 PM" src="https://user-images.githubusercontent.com/78557542/230994058-23402c2c-6ac7-4f74-aec9-10079f15cff8.png">

# ToDo

- [x] Name the main button `Home`
- [ ] Make it translatable
- [x] OnClick  `Home` open the navigation pane
-  [x] OnClick `Testing Home` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/13
- [x] OnClick  `Mapeo Data Is Detected` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/5
- [x] OnClick `Mapeo Is Not Detected` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/14
- [x] OnClick `Invite Device` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/22
- [x] Cannot multi-select
- 
# Designs
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=0-1&t=E6LG66IHUCKXK0Mp-0
