### ISSUE TITLE
Device Selection

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#25]
## Device Selection
User has clicked on the `Invite` button. User can select one of the devices displayed in the modal. 

<img width="871" alt="Screen Shot 2023-04-10 at 4 58 49 PM" src="https://user-images.githubusercontent.com/78557542/230997676-e0c14b81-355f-4a98-8137-1ccf0bb95285.png">

## Todo

- [ ] Build modal as designed
- [ ] Display all the devices as designed
-  [ ] OnClick of one device (cannot multi-select), redirect to https://github.com/digidem/mapeo-desktop-shell/issues/26
-  [ ] Should have a `Cancel` which closes the modal and user lands https://github.com/digidem/mapeo-desktop-shell/issues/22

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=4-623&t=jCsvYtfaEBof4KnS-0
