### ISSUE TITLE
Device Selection/ Role Selection

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#26]
## Device Selection/ Role Selection
User has clicked on the `Invite` button and has selected a device. The modal will display the option to select either a Participant or a Coordinator.

<img width="870" alt="Screen Shot 2023-04-10 at 7 55 03 PM" src="https://user-images.githubusercontent.com/78557542/231021091-7f13f4d7-95fd-4b7d-97c9-4b4285ee7345.png">

## Todo

- [ ] Display modal as designed
- [ ] Display the buttons `Participant` and `Coordinator`
- [ ] OnClick of `Participant` it will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/27
- [ ] `Coordinator` is not clickable
- [ ] Should have a `Cancel` which closes the modal and user lands https://github.com/digidem/mapeo-desktop-shell/issues/22

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=4-623&t=jCsvYtfaEBof4KnS-0
