### ISSUE TITLE
Device Selection/ Success

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#27]
## Device Selection/Success
User has selected a device and the modal displays the success path. 

## Todo
# Step 1
<img width="578" alt="Screen Shot 2023-04-10 at 8 03 06 PM" src="https://user-images.githubusercontent.com/78557542/231021972-53f1466f-4a07-4286-b29a-5d1211142d10.png">

- [ ] Build modal as designed
- [ ] OnClick of `Send Invite` display the step 2

# Step 2 
<img width="592" alt="Screen Shot 2023-04-10 at 8 03 25 PM" src="https://user-images.githubusercontent.com/78557542/231022005-53f0e3fb-544e-4aa2-a937-fec17a475359.png">

- [ ] Display modal content as designed
- [ ] Note from Sabella : 👾  Dev team, this state should reflect the user waiting for someone to accept invite. So sit for 3 to 5 secs?
- [ ] Display **Status** as _Pending_
- [ ] Display `Cancel Invitation` button at the bottom right
- [ ] OnClick of `Cancel Invitation` redirect to https://github.com/digidem/mapeo-desktop-shell/issues/22

# 3
<img width="586" alt="Screen Shot 2023-04-10 at 8 03 42 PM" src="https://user-images.githubusercontent.com/78557542/231022035-716b87e6-ed85-482f-b075-65b8b3e93e84.png">

- [ ] Display **Status** as _Accepted_
- [ ] Display button `Close` which will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/28
- [ ]  `Add Another Device` button is not clickable

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=4-623&t=jCsvYtfaEBof4KnS-0
