### ISSUE TITLE
Project Config / Post-invite

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-desktop-shell#28]
## Project Config / Post-invite
User went through the project invite flow and has successfully invited a device to the project. User is back on the project config screen and see the invited device listed  under Participants

<img width="664" alt="Screen Shot 2023-04-10 at 8 20 00 PM" src="https://user-images.githubusercontent.com/78557542/231023701-506ab80e-ccd5-4a9c-bbb6-17de0ebf0e3e.png">

## Todo

- [ ] Display screen as as designed 
- [ ] OnClick the invited device, in this case called Joy, will redirect to the detail page here https://github.com/digidem/mapeo-desktop-shell/issues/29
- [ ] OnClick of `Leave Project` will redirect to https://github.com/digidem/mapeo-desktop-shell/issues/31

## Design
Full flow here : https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?node-id=4-623&t=jCsvYtfaEBof4KnS-0

**Comment by ximenabb** [comment]
@ErikSin to add technical specs to the ticket
